#!/bin/bash -

#===============================================================================
#        AUTHOR: Yordan Radunchev (), yordan@radunchev.com
#       CREATED: 2017-07-25 23:40
#      REVISION:  001
#===============================================================================

# where to store hosts.txt
ucfg=/etc/unmedia.conf
# root?
[ "$EUID" -ne 0 ] && { echo "Please run as root."; exit 2; }
# backup old unmedia.conf file
[ -f ${ucfg} ] && mv ${ucfg} ${ucfg}.back
# download hosts.txt
wget -O ${ucfg} "https://raw.githubusercontent.com/yradunchev/unmedia/master/hosts.txt";
# restart dnsmasq
killall dnsmasq
dnsmasq --addn-hosts=${ucfg}
