#!/bin/bash -

#===============================================================================
#        AUTHOR: Yordan Radunchev (), yordan@radunchev.com
#       CREATED: 2017-07-24 17:06
#      REVISION:  001
#===============================================================================

# unbound config directory, chahge if you want
ucfg=/etc/unmedia.conf
# root?
[ "$EUID" -ne 0 ] && { echo "Please run as root."; exit 2; }
# backup old unmedia.conf file
[ -f ${ucfg}/unmedia.conf ] && mv ${ucfg}/unmedia.conf ${ucfg}/unmedia.conf.back
# change IFS to new line
IFS=$'\n' 
# read hosts.txt line by line from github
#for a in `wget -q -O - "https://raw.githubusercontent.com/yradunchev/unmedia/master/hosts.txt"`;
for a in $(curl -s "https://raw.githubusercontent.com/yradunchev/unmedia/master/hosts.txt");
do 
  # skip comment lines
  case "$a" in \#*) continue ;; esac 
  # write local-zone redirect and local-data A record for each URL in hosts.txt
  echo "local-zone: \"${a#* }\" redirect" >> ${ucfg}/unmedia.conf;
  echo "local-data: \"${a#* } A 0.0.0.0\"" >> ${ucfg}/unmedia.conf;
done

# restart unbound
systemctl restart unbound
