#!/bin/bash -

#===============================================================================
#        AUTHOR: Yordan Radunchev (), yordan@radunchev.com
#       CREATED: 2017-07-24 17:06
#      REVISION:  001
#===============================================================================

# Output file
ucfg=unmedia.src
# Clear Mikrotik static dns records for unmedia if any
echo "/ip dns static remove [find comment=\"unmedia\"]" > ${ucfg}
echo "/ip dns static" >> ${ucfg}
# change IFS to new line
IFS=$'\n' 
for a in $(curl -s "https://raw.githubusercontent.com/yradunchev/unmedia/master/hosts.src");
  do 
    # skip comment lines
    case "$a" in \#*) continue ;; esac 
    # write local-zone redirect and local-data A record for each URL in hosts.txt
  echo "add address=127.0.0.1 name=${a#* } comment=\"unmedia\"" >> ${ucfg};
done
